[package]
name = "ddc-adapters"
description = "Driven adapters for ddc-control's MonitorBackend port."
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["ddc-hi"]
ddc-hi = ["dep:ddc-hi"]

[dependencies]
ddc-core = { workspace = true }
ddc-hi = { version = "0.4.1", default-features = false, features = ["ddc-i2c", "ddc-winapi"], optional = true }

[lints]
workspace = true
